### ISSUE TITLE
Unable to build with ca65 v2.19 - String constant expected

### ISSUE THREAD

**Issue by charasyn** [Herringway/ebsrc#14]
Hello,
I have just tried building for the first time, but I'm receiving this error:
```
$ make
ca65 -t none --cpu 65816 --bin-include-dir src --include-dir src -D USA --create-dep "src/bankconfig/US/bank00-1.dep" "src/bankconfig/US/bank00-1.asm"
src/macros.asm:19: Error: String constant expected
mingw32-make: *** [Makefile:40: src/bankconfig/US/bank00-1.dep] Error 1
$ ca65 --version
ca65.exe V2.19 - Git 0ae1aad
```
I am not sure who is at fault here, but a string constant should not be expected at that spot, so I'm guessing there's an issue with the ca65 version I am using. Can you confirm which version works for you?
Thanks,
cooprocks123e

**Comment by charasyn** [comment]
Update: I can't read and thought it said line 9 instead of 19. Looking at line 19:
```
.MACRO AUDIOPACK size, target, file
    .WORD size
    .IF size > 0
        .WORD target
        .INCLUDE file ; <<< this one
    .ENDIF
.ENDMACRO
```
That should definitely work. Looking at cc65 github, someone put in a change that broke this:
https://github.com/cc65/cc65/commit/b9a3c7888822732a0de92741cfe1a3e1b6bb272f

So short answer: use a version of cc65 from before May 2nd, 2021.

**Comment by Anonymous941** [comment]
I'm still unable to build it on any version, I just get this error.
