### ISSUE TITLE
Add offsets to the ASM source files?

### ISSUE THREAD

**Issue by Anonymous941** [Herringway/ebsrc#22]
Sorry to post this as an issue, but I've been trying for a long time to add offsets to all of the lines.  For example:

```plain
MENU_SETUP_SELECTED: JSL $c1f3c2 // $c1f872
UNKNOWN7: LDA #$0000 // $c1f876
JSL $c1f497 // $c1f879
CMP #$0000 // $c1f87d
```

I can only find the comments for the beginning of the routines.

**Comment by Herringway** [comment]
I am not sure what exactly it is you are asking for, but I will not be accepting any PRs that add offsets in comments. They are being phased out, as they have little value and are often inaccurate, especially for non-vanilla earthbound builds

**Comment by Anonymous941** [comment]
I'm asking how I can do this not for a PR, but so I can know which offsets I can modify to change subroutines in a ROM hack.  For example, how I would know which byte in the ROM I should modify in order to change the [@RETURN_ALLY_GENDER subroutine in get_gender_etc.asm](https://github.com/Herringway/ebsrc/blob/87f514cb4b77fa3193bcb122ea51f5de5cfdd9cf/src/text/ccs/get_gender_etc.asm#L50C2-L50C2)?

**Comment by Herringway** [comment]
If you modify the subroutine in the .asm file and recompile it, you'd be able to compare the ROM with a vanilla ROM and copy those changes to whatever system you're using

**Comment by Anonymous941** [comment]
Oh, I see, I was approaching this the wrong way.  Thanks for your help
