### ISSUE TITLE
initial_stats.asm is a table

### ISSUE THREAD

**Issue by stochaztic** [Herringway/ebsrc#3]
https://github.com/Herringway/ebsrc/blob/3b0c1d699b74bf4c653ae326aff3d4be96c029fd/src/data/initial_stats.asm#L8

This data is the data for the other three heroes, in exactly the same format as Ness's data above (first four bytes of each entry still unknown to me).

(BTW, not sure if GitHub issues is the best format for sharing discoveries or improvements with you--let me know if you'd prefer something else.)

**Comment by Herringway** [comment]
it's fine but apparently github doesn't notify me in any way

**Comment by Herringway** [comment]
Fixed by efc8eac840c4310873a63aa09403af85892a2b94
