### ISSUE TITLE
Non-matching ROM detected.

### ISSUE THREAD

**Issue by genesis-solution** [Herringway/ebsrc#33]
Hello @Herringway @charasyn 
I'm very interested in making changes to EarthBound mother 2 and so I have just tried to get the source code using ebsrc.

I downloaded the source ROM which has 3072KB and run this code in the command prompt.
`ebbinex mother2.yml "../EarthBound (USA).sfc"`

But I get this response.
`Non-matching ROM detected.`

![image](https://github.com/user-attachments/assets/f69bb167-2228-44f5-b549-d5abfbf9d3d4)

I am sure I put the correct path to the ROM file.
How can I fix?

**Comment by Herringway** [comment]
Use the command that matches your copy of the game. Mother 2 is the Japanese release.

**Comment by genesis-solution** [comment]
Oh, does it?
I am trying the USA version and would you like to give me the command here?

**Comment by genesis-solution** [comment]
I've tried the US command and yes, it works.
Great. Thanks.

One more question, I have some dump files in src/bin directory and is this what we're expecting finally?

**Comment by Herringway** [comment]
I do not know what you are expecting. If you are looking to build a ROM, you just need to read and follow the instructions.

**Comment by genesis-solution** [comment]
Thank you for your responses.
